/*action types*/
export default  {
// Action for ShippingAddress Component
  SET_INPUT_NAME :'SET_INPUT_NAME',
  SET_INPUT_ADDRESS:'SET_INPUT_ADDRESS',
  SET_INPUT_APT:'SET_INPUT_APT',
  SET_INPUT_CITY:'SET_INPUT_CITY',
  SET_INPUT_USSTATE:'SET_INPUT_USSTATE',
  SET_INPUT_ZIP:'SET_INPUT_ZIP',
  SET_INPUT_PHONE:'SET_INPUT_PHONE',
  RESET_INPUT: 'RESET_INPUT',
//Action For UpsLocation Component
  SET_LOCATION: 'SET_LOCATION'
}